"""core schema

Revision ID: 0001
Revises:
Create Date: 2026-09-22
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("demo_now", sa.DateTime(), nullable=False),
        sa.Column("operational_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotels")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=True),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.String(length=40), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("tool_call_id", sa.String(length=100), nullable=True),
        sa.Column("outcome", sa.String(length=40), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("wall_time", sa.DateTime(), nullable=False),
        sa.Column("demo_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_audit_events_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_events_run_id", ["run_id"], unique=False)

    op.create_table(
        "guests",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("selectable", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_guests_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guests")),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("number", sa.String(length=10), nullable=False),
        sa.Column("housekeeping_state", sa.String(length=20), nullable=False),
        sa.Column("out_of_service", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "housekeeping_state IN ('dirty', 'clean', 'inspected')",
            name=op.f("ck_rooms_housekeeping_state"),
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], name=op.f("fk_rooms_hotel_id_hotels")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("hotel_id", "number", name="uq_rooms_hotel_number"),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("guest_id", sa.String(length=40), nullable=False),
        sa.Column("room_id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scheduled_check_in", sa.DateTime(), nullable=False),
        sa.Column("scheduled_checkout", sa.DateTime(), nullable=False),
        sa.Column("actual_check_in", sa.DateTime(), nullable=True),
        sa.Column("actual_checkout", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('confirmed', 'checked_in', 'checked_out', 'cancelled')",
            name=op.f("ck_reservations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"], ["guests.id"], name=op.f("fk_reservations_guest_id_guests")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_reservations_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_reservations_room_id_rooms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
        sa.UniqueConstraint("hotel_id", "reference", name="uq_reservations_hotel_reference"),
    )
    op.create_table(
        "demo_sessions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("capability_hash", sa.String(length=64), nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("guest_id", sa.String(length=40), nullable=False),
        sa.Column("reservation_id", sa.String(length=40), nullable=False),
        sa.Column("room_id", sa.String(length=40), nullable=False),
        sa.Column("conversation_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_turn_count", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("context_restarted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guest_id"], ["guests.id"], name=op.f("fk_demo_sessions_guest_id_guests")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_demo_sessions_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_demo_sessions_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_demo_sessions_room_id_rooms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_sessions")),
        sa.UniqueConstraint("capability_hash", name=op.f("uq_demo_sessions_capability_hash")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("client_request_id", sa.String(length=36), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("final_message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("conversation_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("model_id", sa.String(length=100), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("artifact_refs", sa.JSON(), nullable=False),
        sa.Column("conversation_abandoned", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'interrupted')",
            name=op.f("ck_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["demo_sessions.id"], name=op.f("fk_runs_session_id_demo_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("session_id", "client_request_id", name="uq_runs_session_request"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index("ix_runs_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_status")

    op.drop_table("runs")
    op.drop_table("demo_sessions")
    op.drop_table("reservations")
    op.drop_table("rooms")
    op.drop_table("guests")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_run_id")

    op.drop_table("audit_events")
    op.drop_table("hotels")
    # ### end Alembic commands ###
