"""policy housekeeping receipts

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotel_policies",
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("breakfast_start_local", sa.String(length=5), nullable=False),
        sa.Column("breakfast_end_local", sa.String(length=5), nullable=False),
        sa.Column("housekeeping_items", sa.JSON(), nullable=False),
        sa.Column("housekeeping_max_quantity", sa.Integer(), nullable=False),
        sa.Column("maintenance_categories", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_hotel_policies_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("hotel_id", name=op.f("pk_hotel_policies")),
    )
    op.create_table(
        "operation_receipts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("operation_key", sa.String(length=64), nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("reservation_id", sa.String(length=40), nullable=True),
        sa.Column("session_id", sa.String(length=40), nullable=True),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("client_request_id", sa.String(length=64), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("artifact_type", sa.String(length=40), nullable=True),
        sa.Column("artifact_id", sa.String(length=40), nullable=True),
        sa.Column("committed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_operation_receipts_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_receipts")),
        sa.UniqueConstraint("operation_key", name=op.f("uq_operation_receipts_operation_key")),
    )
    with op.batch_alter_table("operation_receipts", schema=None) as batch_op:
        batch_op.create_index("ix_operation_receipts_run_id", ["run_id"], unique=False)

    op.create_table(
        "housekeeping_tasks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("hotel_id", sa.String(length=40), nullable=False),
        sa.Column("guest_id", sa.String(length=40), nullable=False),
        sa.Column("reservation_id", sa.String(length=40), nullable=False),
        sa.Column("room_id", sa.String(length=40), nullable=False),
        sa.Column("item", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("originating_run_id", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "item IN ('towels', 'pillows', 'room_cleaning')",
            name=op.f("ck_housekeeping_tasks_item"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_housekeeping_tasks_status"),
        ),
        sa.CheckConstraint("quantity BETWEEN 1 AND 6", name=op.f("ck_housekeeping_tasks_quantity")),
        sa.ForeignKeyConstraint(
            ["guest_id"], ["guests.id"], name=op.f("fk_housekeeping_tasks_guest_id_guests")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_housekeeping_tasks_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_housekeeping_tasks_reservation_id_reservations"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_housekeeping_tasks_room_id_rooms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_housekeeping_tasks")),
    )
    with op.batch_alter_table("housekeeping_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_housekeeping_tasks_reservation", ["reservation_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###

    # Data step: an existing demo database from before this revision gets the policy
    # fixture row. A fresh database gets it from the seed.
    conn = op.get_bind()
    if conn.execute(sa.text("SELECT 1 FROM hotels WHERE id = 'hotel_demo'")).first():
        conn.execute(
            sa.text(
                "INSERT INTO hotel_policies (hotel_id, version, breakfast_start_local, "
                "breakfast_end_local, housekeeping_items, housekeeping_max_quantity, "
                "maintenance_categories) VALUES ('hotel_demo', 1, '07:00', '10:30', "
                '\'["towels", "pillows", "room_cleaning"]\', 6, '
                '\'["hvac", "plumbing", "electrical", "other"]\')'
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("housekeeping_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_housekeeping_tasks_reservation")

    op.drop_table("housekeeping_tasks")
    with op.batch_alter_table("operation_receipts", schema=None) as batch_op:
        batch_op.drop_index("ix_operation_receipts_run_id")

    op.drop_table("operation_receipts")
    op.drop_table("hotel_policies")
    # ### end Alembic commands ###
